/**
 * generated by Xtext 2.15.0
 */
package fr.istic;

import fr.istic.AbstractVideoGenRuntimeModule;
import fr.istic.VideoGenValueConverter;
import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class VideoGenRuntimeModule extends AbstractVideoGenRuntimeModule {
  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return VideoGenValueConverter.class;
  }
}
