/**
 * generated by Xtext 2.15.0
 */
package fr.istic.serializer;

import fr.istic.serializer.AbstractVideoGenSyntacticSequencer;

@SuppressWarnings("all")
public class VideoGenSyntacticSequencer extends AbstractVideoGenSyntacticSequencer {
}
