/**
 * generated by Xtext 2.15.0
 */
package fr.istic.serializer;

import fr.istic.serializer.AbstractVideoGenSemanticSequencer;

@SuppressWarnings("all")
public class VideoGenSemanticSequencer extends AbstractVideoGenSemanticSequencer {
}
